### ISSUE TITLE
Add support for Django 3.2

### ISSUE THREAD

**Issue by pythontrade** [django-getpaid/django-plans#130]
As stated in the docs, Django 2 is supported currently. I have tested in Django 3.2 and it does not work currently. Opening issue for improvement for Django 3.2 support.

**Comment by PetrDlouhy** [comment]
I am using current `master` with Django 3.2 and everything works fine. Also the tests are running now in Django 3.2.
Is this outdated, is it request for new PyPI release or do you have any particular problem?
