### ISSUE TITLE
Abstract / Swappable models

### ISSUE THREAD

**Issue by nemesisdesign** [django-getpaid/django-plans#85]
Hi,

are you open to the idea of making the logic in the models of django-plans available as abstract / swappable models (using [django-swappable](https://github.com/wq/django-swappable-models))?

We've been using this approach successfully in some modules of the [OpenWISP project](http://openwisp.org/), eg: [django-freeradius](https://github.com/openwisp/django-freeradius).

OpenWISP needs a way to provide features like premium service and periodic paid subscriptions with expiration. I've been reading the code of this package and another package named silver but I'm more inclined to use this package because it feels a lot simpler. The problem is that obviously I will need to customize a few things to integrate it nicely into OpenWISP and the best way to do that without hacks is to have abstract models.

I did something similar a while ago for django-organizations: https://github.com/bennylope/django-organizations/pull/119.

If you are open to the idea I'm proposing I'm available to join forces with you and improve this package.

**Comment by Alir3z4** [comment]
I'm sorry, somehow this got out of my sight completely. 

I'm fully on this and I like the idea as well.
I see you have made a pull request about it already, thanks for making that happen.

I've left a comment there ;)

**Comment by Alir3z4** [comment]
Hey @nemesisdesign, please let me know if you're not able to complete this or no longer have interest in completing it.
