### ISSUE TITLE
stripe and paypal

### ISSUE THREAD

**Issue by Lifechess** [django-getpaid/django-plans#98]
how can we integrate stripe and paypal

**Comment by PetrDlouhy** [comment]
@Lifechess Both of these providers are supported by [django-payments](https://github.com/mirumee/django-payments). For easier integration, you can use [django-plans-payments](https://github.com/PetrDlouhy/django-plans-payments/commits/master)

**Comment by Lifechess** [comment]
My web site is high-risk type , is it support autorize.net<http://autorize.net>

Envoyé de mon iPad

Le 29 mai 2019 à 03:11, Petr Dlouhý <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Lifechess<https://github.com/Lifechess> Both of these providers are supported by django-payments<https://github.com/mirumee/django-payments>. For easier integration, you can use django-plans-payments<https://github.com/PetrDlouhy/django-plans-payments/commits/master>

**Comment by Alir3z4** [comment]
Closed as best answer to this issue is provided by @PetrDlouhy 

> @Lifechess Both of these providers are supported by [django-payments](https://github.com/mirumee/django-payments). For easier integration, you can use [django-plans-payments](https://github.com/PetrDlouhy/django-plans-payments)
